[package]
name = "float-sim"
version = "0.1.0"
edition = "2021"

[lib]
name = "float_sim"
crate-type = ["rlib", "cdylib"]

[dependencies]
bitvec = "1.0"
num-integer = "0.1.42"
num-bigint = "0.4.3"
num-traits = "0.2.11"
