name: Build and test the library

on: [push]

env:
  RUST_BACKTRACE: full

jobs:
  test:
    name: "Build and test"
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust compiler
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            default: true
            override: true
            components: rustfmt, clippy
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test

  linter:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust compiler
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            default: true
            override: true
            components: rustfmt, clippy
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Format
        run: cargo fmt --all -- --check
